title: My resume
author: Qi Baoli
email: 765074145@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Thank you for coming here.This is my resume.I am a master in HIT.My mayor is mechatronic engineering.

# social links
twitter_username: NONE
github_username:  RockyQBL

show_excerpts: false # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
